package model;
// Generated 6/06/2014 11:50:31 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable {


     private Integer idconductor;
     private int identificacion;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String email;
     private int nroPase;
     private String categoria;
     private Set vehiculos = new HashSet(0);
     private Set recorridos = new HashSet(0);

    public Conductor() {
        this.idconductor = 0;
    }

	
    public Conductor(int identificacion, String nombre, String apellido, String direccion, String telefono, String email, int nroPase, String categoria) {
        this.identificacion = identificacion;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.telefono = telefono;
        this.email = email;
        this.nroPase = nroPase;
        this.categoria = categoria;
    }
    public Conductor(int identificacion, String nombre, String apellido, String direccion, String telefono, String email, int nroPase, String categoria, Set vehiculos, Set recorridos) {
       this.identificacion = identificacion;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.nroPase = nroPase;
       this.categoria = categoria;
       this.vehiculos = vehiculos;
       this.recorridos = recorridos;
    }

    public Integer getIdconductor() {
        return this.idconductor;
    }
    
    public void setIdconductor(Integer idconductor) {
        this.idconductor = idconductor;
    }
   
    public int getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public int getNroPase() {
        return this.nroPase;
    }
    
    public void setNroPase(int nroPase) {
        this.nroPase = nroPase;
    }

    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }

    public Set getRecorridos() {
        return this.recorridos;
    }
    
    public void setRecorridos(Set recorridos) {
        this.recorridos = recorridos;
    }




}


