package model;
// Generated 6/06/2014 11:50:31 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */

public class Estudiante  implements java.io.Serializable {

     private Integer idestudiante;
     private Acudiente acudiente;
     private int identicacion;
     private String nombre;
     private String apellido;
     private String telefono;
     private String direccion;
     private String email;
     private String colegio;
     private String sexo;
     private String jornada;
     private Set detallerecorridoestudiante = new HashSet(0);
     private Set detallefactura = new HashSet(0);

     public Estudiante() {
        this.idestudiante=0;
        this.acudiente = new Acudiente();
    }

	
    public Estudiante(Acudiente acudiente, int identicacion, String nombre, String apellido, String telefono, String direccion, String email, String colegio, String sexo, String jornada) {
        this.acudiente = acudiente;
        this.identicacion = identicacion;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.direccion = direccion;
        this.email = email;
        this.colegio = colegio;
        this.sexo = sexo;
        this.jornada = jornada;
    }
    public Estudiante(Acudiente acudiente, int identicacion, String nombre, String apellido, String telefono, String direccion, String email, String colegio, String sexo, Set detallerecorridoestudiante, String jornada, Set detallefactura) {
       this.acudiente = acudiente;
       this.identicacion = identicacion;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
       this.colegio = colegio;
       this.sexo = sexo;
       this.jornada = jornada;
       this.detallerecorridoestudiante = detallerecorridoestudiante;
       this.detallefactura = detallefactura;
    }
   
    public Integer getIdestudiante() {
        return this.idestudiante;
    }
    
    public void setIdestudiante(Integer idestudiante) {
        this.idestudiante = idestudiante;
    }

    public Acudiente getAcudiente() {
        return this.acudiente;
    }
    
    public void setAcudiente(Acudiente acudiente) {
        this.acudiente = acudiente;
    }

    public int getIdenticacion() {
        return this.identicacion;
    }
    
    public void setIdenticacion(int identicacion) {
        this.identicacion = identicacion;
    }
    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }

    
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    public String getJornada() {
        return jornada;
    }

    public void setJornada(String jornada) {
        this.jornada = jornada;
    }

    public Set getDetallerecorridoestudiante() {
        return detallerecorridoestudiante;
    }

    public void setDetallerecorridoestudiante(Set detallerecorridoestudiante) {
        this.detallerecorridoestudiante = detallerecorridoestudiante;
    }

    public Set getDetallefactura() {
        return detallefactura;
    }

    public void setDetallefactura(Set detallefactura) {
        this.detallefactura = detallefactura;
    }
    
}