package model;
// Generated 6/06/2014 11:50:31 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name="estudiante"
    ,catalog="georutas"
)
public class Estudiante  implements java.io.Serializable {


     private Integer idestudiante;
     private Acudiente acudiente;
     private int identicacion;
     private String nombre;
     private String apellido;
     private String telefono;
     private String direccion;
     private String email;
     private String colegio;
     private String sexo;
     private String jornada;
     private Set recorridos = new HashSet(0);

    public Estudiante() {
        this.idestudiante=0;
        this.acudiente = new Acudiente();
    }

	
    public Estudiante(Acudiente acudiente, int identicacion, String nombre, String apellido, String telefono, String direccion, String email, String colegio, String sexo, String jornada) {
        this.acudiente = acudiente;
        this.identicacion = identicacion;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.direccion = direccion;
        this.email = email;
        this.colegio = colegio;
        this.sexo = sexo;
        this.jornada = jornada;
    }
    public Estudiante(Acudiente acudiente, int identicacion, String nombre, String apellido, String telefono, String direccion, String email, String colegio, String sexo, Set recorridos, String jornada) {
       this.acudiente = acudiente;
       this.identicacion = identicacion;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
       this.colegio = colegio;
       this.sexo = sexo;
       this.jornada = jornada;
       this.recorridos = recorridos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idestudiante", unique=true, nullable=false)
    public Integer getIdestudiante() {
        return this.idestudiante;
    }
    
    public void setIdestudiante(Integer idestudiante) {
        this.idestudiante = idestudiante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdAcudiente", nullable=false)
    public Acudiente getAcudiente() {
        return this.acudiente;
    }
    
    public void setAcudiente(Acudiente acudiente) {
        this.acudiente = acudiente;
    }

    
    @Column(name="Identicacion", nullable=false)
    public int getIdenticacion() {
        return this.identicacion;
    }
    
    public void setIdenticacion(int identicacion) {
        this.identicacion = identicacion;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Telefono", nullable=false, length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Direccion", nullable=false, length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Colegio", nullable=false, length=100)
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }

    
    @Column(name="Sexo", nullable=false, length=20)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="Jornada", nullable=false, length=5)
    public String getJornada() {
        return jornada;
    }

    public void setJornada(String jornada) {
        this.jornada = jornada;
    }
    

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set getRecorridos() {
        return this.recorridos;
    }
    
    public void setRecorridos(Set recorridos) {
        this.recorridos = recorridos;
    }




}


