package model;
// Generated 6/06/2014 11:50:31 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recorrido generated by hbm2java
 */
@Entity
@Table(name="recorrido"
    ,catalog="georutas"
)
public class Recorrido  implements java.io.Serializable {


     private Integer idrecorrido;
     private Estudiante estudiante;
     private Ruta ruta;
     private Conductor conductor;
     private Vehiculo vehiculo;

    public Recorrido() {
    }

    public Recorrido(Estudiante estudiante, Ruta ruta, Conductor conductor, Vehiculo vehiculo) {
       this.estudiante = estudiante;
       this.ruta = ruta;
       this.conductor = conductor;
       this.vehiculo = vehiculo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idrecorrido", unique=true, nullable=false)
    public Integer getIdrecorrido() {
        return this.idrecorrido;
    }
    
    public void setIdrecorrido(Integer idrecorrido) {
        this.idrecorrido = idrecorrido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEstudiante", nullable=false)
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdRuta", nullable=false)
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdConductor", nullable=false)
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdVehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }




}


