package model;
// Generated 6/06/2014 11:50:31 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,catalog="georutas"
    , uniqueConstraints = {@UniqueConstraint(columnNames="IdConductor"), @UniqueConstraint(columnNames="IdRuta")} 
)
public class Vehiculo  implements java.io.Serializable {


     private int idvehiculo;
     private Conductor conductor;
     private Recorrido recorrido;
     private int nroRuta;
     private String placa;
     private String color;
     private Set recorridos = new HashSet(0);

    public Vehiculo() {
        this.idvehiculo = 0;
        this.conductor = new Conductor();
        this.recorrido = new Recorrido();
    }

	
    public Vehiculo(int idvehiculo, Conductor conductor, Recorrido recorrido, int nroRuta, String placa, String color) {
        this.idvehiculo = idvehiculo;
        this.conductor = conductor;
        this.recorrido = recorrido;
        this.nroRuta = nroRuta;
        this.placa = placa;
        this.color = color;
    }
    public Vehiculo(int idvehiculo, Conductor conductor, Recorrido recorrido, int nroRuta, String placa, String color, Set recorridos) {
       this.idvehiculo = idvehiculo;
       this.conductor = conductor;
       this.recorrido = recorrido;
       this.nroRuta = nroRuta;
       this.placa = placa;
       this.color = color;
       this.recorridos = recorridos;
    }
   
     @Id 

    
    @Column(name="idvehiculo", unique=true, nullable=false)
    public int getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(int idvehiculo) {
        this.idvehiculo = idvehiculo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdConductor", unique=true, nullable=false)
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdRecorrido", unique=true, nullable=false)
    public Recorrido getRecorrido() {
        return recorrido;
    }

    public void setRecorrido(Recorrido recorrido) {
        this.recorrido = recorrido;
    }
    
    
    @Column(name="NroRuta", nullable=false)
    public int getNroRuta() {
        return this.nroRuta;
    }
    
    public void setNroRuta(int nroRuta) {
        this.nroRuta = nroRuta;
    }

    
    @Column(name="Placa", nullable=false, length=10)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    
    @Column(name="Color", nullable=false, length=25)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set getRecorridos() {
        return this.recorridos;
    }
    
    public void setRecorridos(Set recorridos) {
        this.recorridos = recorridos;
    }




}


